### ISSUE TITLE
missing settings for xmrig

### ISSUE THREAD

**Issue by Must4che** [minershive/hiveos-linux#101]
Hi,
I'm currently struggling to enable randomx.1gb-pages. I tried to configure it under flightsheet > miner config > extra config args, but that only resulted in error in config.json. So I tried to directly change that config through Hive Shell, but after restarting the miner all settings are reverted(looks like settings from my flightsheet are applied). I also had some issues changing cpu config. All changes in CPU config aldo resulted in error in config.json. Even pasting in the example resulted in same error.

**Comment by bradvanderwielen** [comment]
I have always had that issue as well.  It is unclear how the web GUI and text config.json are supposed to be edited.  I was able to turn it on by editing both the config_global.json and the config.json and change that value to true for both.  But this is certainly something that could be addressed, as I have the same issue and I am sure we are not the only ones.  I suspect most people just leave it going with default settings because touching anything breaks the transfer of data to the config file.

**Comment by HaloGenius** [comment]
it's no linux part
closed
