### ISSUE TITLE
Add RTX 3000 series memory temprature!

### ISSUE THREAD

**Issue by chmichael** [minershive/hiveos-linux#104]
Hello,
  HWInfo has it please add it too!

![hwinfo-rtx](https://user-images.githubusercontent.com/13120950/108576521-9b83f500-7326-11eb-9677-56376d2680ee.jpg)

Thank you

**Comment by HaloGenius** [comment]
Perhaps sometime in the future.

**Comment by chmichael** [comment]
Hello,
  As i see nvidia smi supports vram temps under windows using nvidia-smi ... maybe the latest drivers supports under linux too!
  https://www.hwinfo.com/forum/threads/rtx-3080-3090-memory-vrm-temperature-sensor.6830/
  
  Thank you

**Comment by HaloGenius** [comment]
> 
> 
> Hello,
> As i see nvidia smi supports vram temps under windows using nvidia-smi ... maybe the latest drivers supports under linux too!
> https://www.hwinfo.com/forum/threads/rtx-3080-3090-memory-vrm-temperature-sensor.6830/
> 
> Thank you

Key is "maybe" but don't yet

**Comment by mknippen** [comment]
Adding some comments here as I know many people are trying to figure out why hiveOS doesn't have this:

Because there's no way to grab it in linux right now. Nvidia has not opened it up on linux. You can read more here: https://forums.developer.nvidia.com/t/request-gpu-memory-junction-temperature-via-nvidia-smi-or-nvml-api/168346
